### ISSUE TITLE
Suggestion: Town symbols instead of only having red lines. (#1)

### ISSUE THREAD

**Issue by Agaloth** [silverwolfg11/Pl3xMap-Towny#1]
If you look on the normal dynmap towny, we have town symbols as seen on https://map.terraemc.net

**Comment by silverwolfg11** [comment]
Do you mean like a symbol at every cluster of a town? Currently, only the homeblock of a town gets a town icon. 
I was debating adding a separate icon for outposts that would appear at the outpost spawn, would that work?

**Comment by Agaloth** [comment]
Yeah that should work, you could give some screenshots here and I can tell you if it's good or not :D

**Comment by silverwolfg11** [comment]
Outpost icons have been added in build Alpha 2 which is available on the releases page.
