### ISSUE TITLE
Bug: Town claims are triangular and very off (#2)

### ISSUE THREAD

**Issue by Agaloth** [silverwolfg11/Pl3xMap-Towny#2]
It has the same bug as when first pl3xmap released when the claims were seen as triangular and not the usual square ones.

https://user-images.githubusercontent.com/33335971/110360305-d97b5b80-803e-11eb-93b6-b013292c254b.png

**Comment by silverwolfg11** [comment]
Hmmm weird. In order to figure out the issue, I need to see what it is supposed to look like.  Please do `/towny map big` in-game and post the screenshot of the claim map here and that will help me figure out what shape is not being drawn correctly.

**Comment by Agaloth** [comment]
It was a few months ago and since pl3xmap towny had memory leaks I had to give up using it and move back to dynmap.

**Comment by silverwolfg11** [comment]
Well, unfortunately without steps or anything replicate the issue, I cannot really fix it.

**Comment by Agaloth** [comment]
The only thing that I know is that, this was happening for every town, to reproduce it on the old version, I did a town in a shape of L or X and it would do that

**Comment by silverwolfg11** [comment]
If there's no way to replicate the issue, I'm going to close this. 

In fact, I noticed that this was the same image you posted on the other Pl3xMap-Towny Repo. To clarify, this repo is an entirely rewritten version of the plugin, so please test with this plugin before creating bug issues (and even suggestion issues). 

I have already tested the basic shapes you stated above, and there are even unit tests for basic shapes like those, so I know that it works fine with simple  L shapes and the sort.
