### ISSUE TITLE
Suggestion: More placeholders + being able to change the nation placeholder saying _none_ (#3)

### ISSUE THREAD

**Issue by Agaloth** [silverwolfg11/Pl3xMap-Towny#3]
Basically, it would be cool to have a way to modify the none to only none for the nation placeholder and also having a lot of new placeholders like on the original dynmap-towny. (https://github.com/TownyAdvanced/Dynmap-Towny/wiki).

**Comment by silverwolfg11** [comment]
I don't quite understand what you mean by your first request. But I can definitely look into adding more placeholders like Dynamp-Towny has!

**Comment by Agaloth** [comment]
It must've modified my comment when I copy-pasted it, basically I meant that you could add a placeholder that let's us modify the "none" text when no one has a nation so that way we can set up something ourselves for it like "Nationless" etc...

**Comment by silverwolfg11** [comment]
More placeholders have been added in build Alpha 2 which is available on the releases page. The placeholders should match Dynmap-Towny parity now. As for the configurable "None" setting. That may be available in a future build, but is currently not a high priority at the moment.
