### ISSUE TITLE
Suggestion: Nation colors for the claims. (#4)

### ISSUE THREAD

**Issue by Agaloth** [silverwolfg11/Pl3xMap-Towny#4]
Basically, it would be cool to have a command in-game like /n set color {red, blue, yellow, green, etc...} where nations can set their nation colors with some preset colors.

**Comment by silverwolfg11** [comment]
This is already implemented in Towny and can be set via `/nation set mapcolor [hex color]`. See [this](https://github.com/TownyAdvanced/Towny/wiki/Towny-Commands#nation) for a list of nation commands.
