### ISSUE TITLE
Suggestion: Option to hide underground players + players sneaking (#5)

### ISSUE THREAD

**Issue by Agaloth** [silverwolfg11/Pl3xMap-Towny#5]
Basically, a config line which will allow you to toggle hiding players underground (when they mine, etc...) then another line that makes so players using shift to sneak won't be seen on the map.

**Comment by silverwolfg11** [comment]
This request would make sense more for the scope of Pl3xMap rather than this plugin. This plugin doesn't really deal with the behavior of player markers,  so it wouldn't make sense for this plugin to implement that behavior.
I would recommend making that suggestion on the Pl3xMap github!
