### ISSUE TITLE
Suggestion: Siege War Support

### ISSUE THREAD

**Issue by Romvnly-Gaming** [silverwolfg11/Pl3xMap-Towny#8]
I'd like to see Pl3xMap-Towny support:
- Town Color ([From Dynmap Siege War Wiki](https://github.com/TownyAdvanced/SiegeWar/wiki/Siege-War-User-Guide))
- Map Sneak - To disappear from Pl3xMap (During War)

**Comment by silverwolfg11** [comment]
I can expose API for adding replacements, so SiegeWar can utilize that for the first request. However, for your second request, this plugin does not touch player markers on the map (since it is out of scope), so that is something better suggested directly on the SiegeWar github.

**Comment by silverwolfg11** [comment]
I have added the necessary API for SiegeWar to hook into with the release of version [Alpha-3](https://github.com/silverwolfg11/Pl3xMap-Towny/releases/tag/v1.0.0-alpha-3).  I will look into making the necessary issue on the SiegeWar repo (if one doesn't exist), and possibly a PR.
